[package]
name = "ferrox"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }
proptest = "1.10.0"

[[bench]]
name = "matching_bench"
harness = false

[[bench]]
name = "ring_bench"
harness = false
